### ISSUE TITLE
Where is the rootfs tarball ?

### ISSUE THREAD

**Issue by rbarris** [krtkl/snickerdoodle-manual#4]
"snickerdoodle-ubuntu-14.04.tar.gz" is referenced in the documentation (page 8 of the quickstart), but where is it online ?

(echoing Nick Burkitt's post from the krtkl forum)

**Comment by Weatherbee** [comment]
Rob, I am looking into the location of this file stat.
We are uploading it now and will share the URL shortly.

**Comment by Weatherbee** [comment]
Here is a permanent link to the root filesystem tarball: https://krtkl.sharefile.com/d-s66b125f5dec4d5d9

**Comment by rasovica** [comment]
Link Expired

The link you are trying to access is no longer available.
