### ISSUE TITLE
No sources available for the pdf documents

### ISSUE THREAD

**Issue by come-maiz** [krtkl/snickerdoodle-manual#7]
Instead of uploading static pdf documents to the git repository, it would be a lot better to provide the source files that generate those pdfs. That way we could change the sources directly and make a pull request with the suggested changes.

Even something less visually attractive like markdown files are better for documentation, because they are easier to modify and improve.

**Comment by come-maiz** [comment]
Another argument for markdown or something similar instead of pdf: copy and paste from pdf sucks. Many times I've copied incomplete commands, which in the case of this guide could result in something terrible for the other usb devices attached to my machine.

**Comment by russbush** [comment]
PDF documents will not be replaced but will be supplemented with additional documentation in the form of markdown, etc. The documentation is/will be presented in multiple forms to allow people to digest the information in whatever form works best for them. That being said, the source for the PDFs (LaTeX) may be provided in the future.

**Comment by come-maiz** [comment]
Could you keep this bug open until the sources are published? Latex is totally acceptable for me.

**Comment by russbush** [comment]
LaTeX source added

**Comment by come-maiz** [comment]
woohoo \o/
Do you want me to send a PR fixing the errors I found?

**Comment by russbush** [comment]
Yes, please. I've already fixed some of the errors and made a few updates.
